app = "<prefix>-clickhouse"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []
services = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[mounts]]
  source = "<prefix>_clickhouse_data"
  destination = "/var/lib/clickhouse"
